name: Nuevo Cliente
  
on: 
  push:
  
jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        
      - name: Notificacion
        run: echo"Se ha creado un nuevo cliente. Notificacion del equipo de AXA"
