name: Consultar Cliente
  
on: 
  push:
  
jobs:
  notificar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
    
      - name: Notificacion
        run: echo "Consulta del cliente realizada. Notificacion del equipo de AXA"
